name: Node.js CI

on:

push:

branches: [ master ]

pull_request:

branches: [ master ]

jobs:

build:

runs-on: ubuntu-latest

services:

mysql:

image: mysql:5.7

env:

MYSQL_ROOT_PASSWORD: vini4513

MYSQL_DATABASE: usersdb

ports:

- 3306:3306

steps:

- uses: actions/checkout@v2

- name: Use Node.js

uses: actions/setup-node@v1

with:

node-version: '14'

- name: Install dependencies

run: npm install

- name: Start MySQL

run: sudo /etc/init.d/mysql start

- name: Install client mysql

run: sudo apt install mysql-client

- name: Criar tabelas

run: sudo mysql -h localhost -u root -p vini4513 usersdb < structure.sql

- name: Run tests

run: npm test